name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC
  workflow_dispatch:    # allows manual trigger

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs."
          stale-pr-message: "This PR has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs."
          days-before-stale: 14
          days-before-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "help-wanded, good first issue"
